---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: fieldtext1
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: FieldText1
  description: Description123
pages:
- projects/molecular-gastronomy.md
- projects/the-london-book-fair.md
- projects/tytul.md
- projects/°-jupiter-calendar.md
